before:
  hooks:
    - go install golang.org/x/tools/...@latest
    - go mod tidy
    - go generate ./...
builds:
  - 
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X github.com/hazelcast/hazelcast-go-client/internal.ClientVersion={{.Version}} -X github.com/hazelcast/hazelcast-commandline/client/internal.CommitSHA={{.Version}} -X github.com/hazelcast/hazelcast-go-client/internal.ClientType=CLC"
    binary: hzc
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - 
    id: default
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    files:
      - extras/*
      - scripts/uninstall.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# .goreleaser.yaml
